### ISSUE TITLE
bignum.wasm was renamed to as-bignum and published to npm

### ISSUE THREAD

**Issue by MaxGraey** [paritytech/pallet-contracts-waterfall#37]
github: https://github.com/MaxGraey/as-bignum
npm: https://www.npmjs.com/package/as-bignum

**Comment by Stefie** [comment]
Ah, great, I'll update it in the dependencies! Thanks for letting us know!

**Comment by Stefie** [comment]
I'm getting a compile error with the latest (2 months old) stable version of AssemblyScript . I should probably either switch to nightly or wait for the next stable release.
```
ERROR: Import file '~lib/bignum.ts' not found.
    at parseBacklog (/Users/stefaniedoll/Parity/ParityJS/pallet-contracts-waterfall/contracts/assemblyscript/flipper/node_modules/assemblyscript/cli/asc.js:397:34)
    at Object.main (/Users/stefaniedoll/Parity/ParityJS/pallet-contracts-waterfall/contracts/assemblyscript/flipper/node_modules/assemblyscript/cli/asc.js:450:16)
    at Object.<anonymous> (/Users/stefaniedoll/Parity/ParityJS/pallet-contracts-waterfall/contracts/assemblyscript/flipper/node_modules/assemblyscript/bin/asc:21:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
error Command failed with exit code 1.
```

**Comment by MaxGraey** [comment]
Is it with `as-bignum`?
```ts
import { u128 } from "as-bignum";
```

**Comment by MaxGraey** [comment]
I specially checked and with `"as-bignum"` should work.

**Comment by Stefie** [comment]
That's what happens when you quickly update stuff between doing other things :| . I updated the imports in my other repos, but forgot to update them here...
Works perfectly well now!
